/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dental_clinic_management_system;

/**
 *
 * @author JESSA MARIE BEBITA
 */
public class HOMEPAGE extends javax.swing.JFrame {

    /**
     * Creates new form HOMEPAGE
     */
    public HOMEPAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        goappointment = new javax.swing.JButton();
        gotreatment = new javax.swing.JButton();
        gohistory = new javax.swing.JButton();
        goschedule = new javax.swing.JButton();
        gobill = new javax.swing.JButton();
        goregistration = new javax.swing.JButton();
        gotreatmentdeatails = new javax.swing.JButton();
        gologout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("DENTAL CLINIC MANAGEMENT SYSTEM");

        goappointment.setText("APPOINTMENT");
        goappointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goappointmentActionPerformed(evt);
            }
        });

        gotreatment.setText("TREATMENT DETAILS");
        gotreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotreatmentActionPerformed(evt);
            }
        });

        gohistory.setText("HISTORY");
        gohistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gohistoryActionPerformed(evt);
            }
        });

        goschedule.setText("SCHEDULE");
        goschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goscheduleActionPerformed(evt);
            }
        });

        gobill.setText("BILL");
        gobill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobillActionPerformed(evt);
            }
        });

        goregistration.setText("REGISTRATION");
        goregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goregistrationActionPerformed(evt);
            }
        });

        gotreatmentdeatails.setText("TREATMENT ");
        gotreatmentdeatails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotreatmentdeatailsActionPerformed(evt);
            }
        });

        gologout.setText("LOG OUT");
        gologout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gologoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(goappointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gohistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gobill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(goschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gotreatmentdeatails, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(goregistration)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(gologout)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gotreatment)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goappointment)
                    .addComponent(goregistration))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gotreatmentdeatails)
                    .addComponent(gotreatment))
                .addGap(18, 18, 18)
                .addComponent(goschedule)
                .addGap(18, 18, 18)
                .addComponent(gohistory)
                .addGap(18, 18, 18)
                .addComponent(gobill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(gologout)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goappointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goappointmentActionPerformed
        // TODO add your handling code here:
        appointment obj = new appointment();
        obj.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_goappointmentActionPerformed

    private void gotreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotreatmentActionPerformed
        // TODO add your handling code here:
        detailstreatment obj = new detailstreatment();
        obj.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_gotreatmentActionPerformed

    private void goscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goscheduleActionPerformed
        // TODO add your handling code here:
       schedule obj = new schedule();
        obj.setVisible(true);
           dispose();
    }//GEN-LAST:event_goscheduleActionPerformed

    private void gologoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gologoutActionPerformed
        // TODO add your handling code here:
        loginpage obj = new loginpage();
        obj.setVisible(true);
           dispose();
    }//GEN-LAST:event_gologoutActionPerformed

    private void gohistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gohistoryActionPerformed
        // TODO add your handling code here:
         history obj = new history();
        obj.setVisible(true);
           dispose();
    }//GEN-LAST:event_gohistoryActionPerformed

    private void gobillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobillActionPerformed
        // TODO add your handling code here:
         bill obj = new bill();
        obj.setVisible(true);
           dispose();
    }//GEN-LAST:event_gobillActionPerformed

    private void goregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goregistrationActionPerformed
        // TODO add your handling code here:
         registrationpage obj = new registrationpage();
        obj.setVisible(true);
           dispose();
    }//GEN-LAST:event_goregistrationActionPerformed

    private void gotreatmentdeatailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotreatmentdeatailsActionPerformed
        // TODO add your handling code here:
        treatmentdetails obj = new treatmentdetails();
        obj.setVisible(true);
           dispose();
    }//GEN-LAST:event_gotreatmentdeatailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOMEPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOMEPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOMEPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOMEPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOMEPAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goappointment;
    private javax.swing.JButton gobill;
    private javax.swing.JButton gohistory;
    private javax.swing.JButton gologout;
    private javax.swing.JButton goregistration;
    private javax.swing.JButton goschedule;
    private javax.swing.JButton gotreatment;
    private javax.swing.JButton gotreatmentdeatails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
